update configure & Makefile

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,13 +3,10 @@
 # For more information, please refer to <http://unlicense.org/>
 #
 
-APP_CFLAGS='-Wall -g -O2 -DHAVE_CONFIG_H'
-APP_CXXFLAGS="${APP_CFLAGS}"
-#APP_CPPFLAGS='-Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers'
-APP_LDFLAGS=''
-APP_LXXFLAGS=''
-APP_LIBS=''
-#W_SYSROOT_PLUS_INCLUDES_AND_LIBS=1
+if ! [ -f Makefile ] ; then
+	echo 'Main Makefile is missing, cannot continue'
+	exit 1
+fi
 
 if ! cd $(dirname "$0") ; then
 	exit 1
@@ -17,7 +14,9 @@ fi
 
 apps_to_check=''
 extra_env_vars=''
+make_extra_flags='' # config_mk_extra
 config_h_extra=''
+config_sh_extra=''
 extra_configure_opts=''
 config_h_have=
 config_mk_flags=
@@ -43,21 +42,37 @@ PACKAGE_VERSION="${VERSION}"
 # ./configure release [xz|gz|lz|bz2|zst]
 
 if [ "$1" = "release" ] ; then
-	if command -v git >/dev/null; then
-		printf "Run 'git clean -dfx'? [y/N]: "
-		read anzwer
-		case $anzwer in y|Y)
-			echo '# git clean -dfx'
-			git clean -dfx ;;
-		esac
-	fi
-	dir=${PACKAGE}-${VERSION}
-	rm -rf ../${dir}
-	mkdir -p ../${dir}
-	cp -rf $(pwd)/* ../${dir}
+	srcdir=$(pwd)
+	outdir=${PACKAGE}-${VERSION}
 	cd ..
-	echo "# tar -vcf ${dir}.tar $dir"
-	tar -vcf ${dir}.tar $dir
+	rm -rf ${outdir}
+	if [ "$2" = "dist" ] ; then
+		# force creation of tarfile, copy the whole dir
+		shift
+		shift
+		cp -rf ${srcdir} ${outdir}
+		cd ${outdir}
+		git clean -dfx
+		rm -rf .*
+		cd ..
+	else
+		if command -v git >/dev/null; then
+			printf "Run 'git clean -dfx'? [y/N]: "
+			read anzwer
+			case $anzwer in y|Y)
+				cd ${srcdir}
+				echo '# git clean -dfx'
+				git clean -dfx
+				cd ..
+				;;
+			esac
+		fi
+		mkdir -p ${outdir}
+		cp -rf ${srcdir}/* ${outdir}/
+	fi
+	#--
+	echo "# tar -vcf ${outdir}.tar ${outdir}"
+	tar -vcf ${outdir}.tar ${outdir}
 	comp=$2
 	if [ -z "$comp" ] ; then
 		comp=xz
@@ -69,16 +84,16 @@ if [ "$1" = "release" ] ; then
 		zst) cmd=zstd    ;;
 		*)   cmd=${comp} ;;
 	esac
-	rm -f ${dir}.tar.${comp}
-	echo "# ${cmd} ${dir}.tar"
-	if ${cmd} ${dir}.tar ; then
-		echo "*** ${dir}.tar.${comp} has been created..."
+	rm -f ${outdir}.tar.${comp}
+	echo "# ${cmd} ${outdir}.tar"
+	if ${cmd} ${outdir}.tar ; then
+		echo "*** ${outdir}.tar.${comp} has been created..."
 	fi
-	rm -f ${dir}.tar
+	rm -f ${outdir}.tar
 	exit
 fi
 
-# w_conf/gettext: ./configure po|pot|po2c
+# w_conf/gettext: ./configure po|pot
 
 #==========================================================
 
@@ -289,7 +304,10 @@ w_check_header_and_libs() # 1:<header> 2-:[libs] is optional
 	else
 		printf "Checking for ${xheaderx}... "
 	fi
-	ccode="#include <${xheaderx}>
+	ccode="#include <stdio.h>
+#include <stdlib.h>
+#include <inttypes.h>
+#include <${xheaderx}>
 int main (int argc, char **argv) { return 0; }
 "
 	w_compile_c_code "$ccode" "" "${xlibsx}"
@@ -340,6 +358,22 @@ w_check_headers_required()
 	done
 }
 
+
+w_check_cflag()
+{
+	printf "Checking if $1 is supported... "
+	c_code='int main (int argc, char **argv) { return 0; }'
+	w_compile_c_code "$ccode" ${1}
+	if [ $? -eq 0 ] ; then
+		echo "yes"
+		return 0
+	else
+		echo "no"
+		return 1
+	fi
+}
+
+
 w_check_command() # sets $wtmp_cmd
 {
 	printf "Checking for $1... "
@@ -386,22 +420,31 @@ w_check_command_find_first() # sets $wtmp_cmd
 }
 
 
-w_require_gnu_make()
+w_prefer_gnu_make() # param: require
 {
 	printf "Checking for GNU make... "
 	if [ -n "$MAKE" ] && "$MAKE" --version 1>/dev/null 2>&1 ; then
 		echo "$MAKE (environment)"
-		W_GNU_MAKE="MAKE = $MAKE"
+		W_GNU_MAKE="MAKE=$MAKE"
 	elif make --version 1>/dev/null 2>&1 ; then
 		echo "make"
+		W_GNU_MAKE='MAKE=make'
 	elif gmake --version 1>/dev/null 2>&1 ; then
 		echo "gmake"
-		W_GNU_MAKE='MAKE = gmake'
+		W_GNU_MAKE='MAKE=gmake'
 	else
 		echo "no"
-		exit_error "ERROR: GNU make is required"
+		if [ -n "$1" ] ; then
+			exit_error "ERROR: GNU make is required"
+		fi
 	fi
 }
+
+w_require_gnu_make()
+{
+	w_prefer_gnu_make require
+}
+
 
 #==========================================================
 
@@ -415,6 +458,10 @@ test "$RANLIB" || RANLIB='ranlib'
 test "$OBJCOPY" || OBJCOPY='objcopy'
 test "$OBJDUMP" || OBJDUMP='objdump'
 static_link=''
+# mingw
+test "$DLLTOOL" || DLLTOOL='dlltool'
+test "$WINDRES" || WINDRES='windres'
+test "$WINDMC"  || WINDMC='windmc'
 
 prefix=/usr/local
 exec_prefix='${prefix}'
@@ -570,6 +617,9 @@ do
 		AR=*)    AR="$(getvalue $i)"     ;;
 		AS=*)    AS="$(getvalue $i)"     ;;
 		NM=*)    NM="$(getvalue $i)"     ;;
+		DLLTOOL=*) DLLTOOL="$(getvalue $i)" ;;
+		WINDRES=*) WINDRES="$(getvalue $i)" ;;
+		WINDMC=*)  WINDMC="$(getvalue $i)" ;;
 
 		--prefix=*)     prefix="$(getvalue $i)"     ;;
 		--exec_prefix=*) exec_prefix="$(getvalue $i)"     ;;
@@ -578,7 +628,6 @@ do
 		--sbindir=*)    sbindir="$(getvalue $i)"    ;;
 		--libexecdir=*) libexecdir="$(getvalue $i)" ;;
 		--includedir=*) includedi="$(getvalue $i)"  ;;
-		--oldincludedir=*)  oldincludedi="$(getvalue $i)" ;;
 		--datarootdir=*)   datarootdir="$(getvalue $i)"   ;;
 		--datadir=*)    datadir="$(getvalue $i)"          ;;
 		--localstatedir=*) localstatedir="$(getvalue $i)" ;;
@@ -611,13 +660,19 @@ set_cc
 set_cxx
 set_w_pkg_config
 
+OS_BUILD=$(uname -s)
+OS_CROSS=''
+OS_TARGET=''
+
 if test -n "$host" ; then
 	printf "Checking cross-compiler... "
 	CROSS_IS_FULL_PATH=''
 	CROSS_BASE_DIR=''
+	OS_CROSS="$host"
 	case $host in /*)
 		CROSS_IS_FULL_PATH=1
 		CROSS_BASE_DIR="$(dirname $host)/"
+		OS_CROSS="$(basename $host)"
 		;;
 	esac
 	cross_base_dir=''
@@ -646,6 +701,11 @@ if test -n "$host" ; then
 		RANLIB=${CROSS_BASE_DIR}${host}-${RANLIB}
 		OBJCOPY=${CROSS_BASE_DIR}${host}-${OBJCOPY}
 		OBJDUMP=${CROSS_BASE_DIR}${host}-${OBJDUMP}
+		#--
+		DLLTOOL=${CROSS_BASE_DIR}${host}-${DLLTOOL}
+		WINDRES=${CROSS_BASE_DIR}${host}-${WINDRES}
+		WINDMC=${CROSS_BASE_DIR}${host}-${WINDMC}
+		#--
 		echo "$host"
 	else
 		exit_error "not found"
@@ -691,12 +751,34 @@ fi
 
 #==========================================================
 
-CFLAGS="$CFLAGS $APP_CFLAGS"
-CPPFLAGS="$CPPFLAGS $APP_CPPFLAGS"
-CXXFLAGS="$CXXFLAGS $APP_CXXFLAGS"
-LDFLAGS="$LDFLAGS $APP_LDFLAGS"
-LXXFLAGS="$LXXFLAGS $APP_LXXFLAGS"
-LIBS="$LIBS $APP_LIBS"
+case ${OS_BUILD} in
+	CYGWIN*) OS_BUILD="Cygwin" ;;
+	MINGW*)  OS_BUILD="MinGW"  ;;
+	MSYS*)   OS_BUILD="MinGW"  ;;
+esac
+
+OS_TARGET=${OS_BUILD}
+
+if [ -n "$OS_CROSS" ] ; then
+	# cross-compiling, reset OS_TARGET
+	OS_TARGET=''
+	# determine OS_TARGET again
+	case $OS_CROSS in
+		*-mingw*)   OS_TARGET='MinGW'   ;;
+		*-darwin*)  OS_TARGET='Darwin'  ;;
+		*-linux-*)  OS_TARGET='Linux'   ;;
+		*-freebsd*) OS_TARGET='FreeBSD' ;;
+	esac
+fi
+
+#==========================================================
+
+CFLAGS="$CFLAGS $PROJECT_CFLAGS"
+CPPFLAGS="$CPPFLAGS $PROJECT_CPPFLAGS"
+CXXFLAGS="$CXXFLAGS $PROJECT_CXXFLAGS"
+LDFLAGS="$LDFLAGS $PROJECT_LDFLAGS"
+LXXFLAGS="$LXXFLAGS $PROJECT_LXXFLAGS"
+LIBS="$LIBS $PROJECT_LIBS"
 
 #==========================================================
 
@@ -726,38 +808,16 @@ do
 done
 
 #==========================================================
-#             config.mk and Makefiles
+#                  config.mk
 #==========================================================
 
-if [ -z "$W_MAKEFILES_IN" ] ; then
-	w_makefiles=
-else
-	w_makefiles=$(find . -name Makefile.in | sed -e 's%.in%%')
-fi
+# ensure -DHAVE_CONFIG_H
+CFLAGS="-DHAVE_CONFIG_H $CFLAGS "
+CXXFLAGS="-DHAVE_CONFIG_H $CXXFLAGS"
 
-for makefile in config.mk ${w_makefiles}
-do
-	cat > ${makefile} <<EOF
+cat > config.mk <<EOF
 # generated by ./configure
 ${W_GNU_MAKE}
-CC = ${CC}
-CXX = ${CXX}
-STRIP = ${STRIP}
-AR = ${AR}
-AS = ${AS}
-NM = ${NM}
-RANLIB = ${RANLIB}
-OBJCOPY = ${OBJCOPY}
-OBJDUMP = ${OBJDUMP}
-
-CFLAGS = ${CFLAGS}
-CPPFLAGS = ${CPPFLAGS}
-CXXFLAGS = ${CXXFLAGS}
-LXXFLAGS = ${LXXFLAGS}
-LDFLAGS = ${LDFLAGS}
-LIBS = ${LIBS}
-
-#=================================================
 
 prefix = ${prefix}
 exec_prefix = ${exec_prefix}
@@ -766,7 +826,6 @@ bindir = ${bindir}
 sbindir = ${sbindir}
 libexecdir = ${libexecdir}
 includedir = ${includedir}
-oldincludedir = ${oldincludedir}
 datarootdir = ${datarootdir}
 datadir = ${datadir}
 localstatedir = ${localstatedir}
@@ -781,6 +840,8 @@ top_srcdir = ${top_srcdir}
 builddir = ${builddir}
 srcdir = ${srcdir}
 
+#=================================================
+
 INSTALL = install -c
 INSTALL_DATA = install -c -m 644
 
@@ -793,30 +854,147 @@ PACKAGE_TARNAME = ${PACKAGE_TARNAME}
 PACKAGE_BUGREPORT = ${PACKAGE_BUGREPORT}
 PACKAGE_VERSION = ${PACKAGE_VERSION}
 
+OS_BUILD = ${OS_BUILD}
+OS_CROSS = ${OS_CROSS}
+OS_TARGET = ${OS_TARGET}
+
+#=================================================
+
+CC = ${CC}
+CXX = ${CXX}
+STRIP = ${STRIP}
+AR = ${AR}
+AS = ${AS}
+NM = ${NM}
+RANLIB = ${RANLIB}
+OBJCOPY = ${OBJCOPY}
+OBJDUMP = ${OBJDUMP}
+
+DLLTOOL = ${DLLTOOL}
+WINDRES = ${WINDRES}
+WINDMC = ${WINDMC}
+
+CFLAGS = ${CFLAGS}
+CPPFLAGS = ${CPPFLAGS}
+CXXFLAGS = ${CXXFLAGS}
+LXXFLAGS = ${LXXFLAGS}
+LDFLAGS = ${LDFLAGS}
+LIBS = ${LIBS}
+
 #=================================================
 ${make_extra_flags}
-
+${w_config_mk_extra_lines}
 EOF
-	if [ -n "${config_mk_flags}" ] ; then
-		(
-			for env in ${config_mk_flags}
-			do
-				echo "${env}_CFLAGS = $(eval echo \$${env}_CFLAGS)"
-				echo "${env}_LIBS   = $(eval echo \$${env}_LIBS)"
-			done
-		) >> ${makefile}
-	fi
 
-	if [ -n "${w_config_mk_extra_lines}" ] ; then
-		echo "${w_config_mk_extra_lines}" >> ${makefile}
-	fi
+if [ -n "${config_mk_flags}" ] ; then
+	(
+		for env in ${config_mk_flags}
+		do
+			echo "${env}_CFLAGS = $(eval echo \$${env}_CFLAGS)
+${env}_LIBS  = $(eval echo \$${env}_LIBS)"
+		done
+	) >> config.mk
+fi
 
-	if [ -f ${makefile}.in ] ; then
-		cat ${makefile}.in >> ${makefile}
-	fi
+#==========================================================
+#                  config.sh (=config.mk)
+#==========================================================
 
-done
+cat > config.sh <<EOF
+#generated by ./configure
 
+prefix="${prefix}"
+exec_prefix="${exec_prefix}"
+libdir="${libdir}"
+bindir="${bindir}"
+sbindir="${sbindir}"
+libexecdir="${libexecdir}"
+includedir="${includedir}"
+datarootdir="${datarootdir}"
+datadir="${datadir}"
+localstatedir="${localstatedir}"
+sysconfdir="${sysconfdir}"
+docdir="${docdir}"
+infodir="${infodir}"
+mandir="${mandir}"
+localedir="${localedir}"
+runstatedir="${runstatedir}"
+top_builddir="${top_builddir}"
+top_srcdir="${top_srcdir}"
+builddir="${builddir}"
+srcdir="${srcdir}"
+
+#=================================================
+
+INSTALL="install -c"
+INSTALL_DATA="install -c -m 644"
+
+PACKAGE="${PACKAGE}"
+VERSION="${VERSION}"
+PACKAGE_URL="${PACKAGE_URL}"
+PACKAGE_NAME="${PACKAGE_NAME}"
+PACKAGE_STRING="${PACKAGE_STRING}"
+PACKAGE_TARNAME="${PACKAGE_TARNAME}"
+PACKAGE_BUGREPORT="${PACKAGE_BUGREPORT}"
+PACKAGE_VERSION="${PACKAGE_VERSION}"
+
+OS_BUILD="${OS_BUILD}"
+OS_CROSS="${OS_CROSS}"
+OS_TARGET="${OS_TARGET}"
+
+#=================================================
+
+CC="${CC}"
+CXX="${CXX}"
+STRIP="${STRIP}"
+AR="${AR}"
+AS="${AS}"
+NM="${NM}"
+RANLIB="${RANLIB}"
+OBJCOPY="${OBJCOPY}"
+OBJDUMP="${OBJDUMP}"
+
+DLLTOOL="${DLLTOOL}"
+WINDRES="${WINDRES}"
+WINDMC="${WINDMC}"
+
+CFLAGS="${CFLAGS}"
+CPPFLAGS="${CPPFLAGS}"
+CXXFLAGS="${CXXFLAGS}"
+LXXFLAGS="${LXXFLAGS}"
+LDFLAGS="${LDFLAGS}"
+LIBS="${LIBS}"
+
+#=================================================
+${config_sh_extra}
+EOF
+
+if [ -n "${config_mk_flags}" ] ; then
+	(
+		for env in ${config_mk_flags}
+		do
+			echo "${env}_CFLAGS=\"$(eval echo \$${env}_CFLAGS)\"
+${env}_LIBS=\"$(eval echo \$${env}_LIBS)\""
+		done
+	) >> config.sh
+fi
+
+
+#==========================================================
+#                  Makefiles.in
+#==========================================================
+
+if [ -n "$W_MAKEFILES_IN" ] ; then
+	w_makefiles=$(find . -name Makefile.in | sed -e 's%\.in%%')
+	for makefile in ${w_makefiles}
+	do
+		cat config.mk ${makefile}.in > ${makefile}
+	done
+fi
+
+#==========================================================
+
+. ./config.sh
 
 #==========================================================
 #                       config.h
@@ -836,15 +1014,13 @@ cat > config.h <<EOF
 #define PACKAGE_BUGREPORT "${PACKAGE_BUGREPORT}"
 #define PACKAGE_VERSION "${PACKAGE_VERSION}"
 
-#define PREFIX "$(print_eval_var $prefix)"
-#define DOCDIR "$(print_eval_var $docdir)"
-#define LOCALEDIR "$(print_eval_var $localedir)"
-#define DATADIR "$(print_eval_var $datadir)"
-#define SYSCONFDIR "$(print_eval_var $sysconfdir)"
+#define PREFIX "$prefix"
+#define DOCDIR "$docdir"
+#define LOCALEDIR "$localedir"
+#define DATADIR "$datadir"
+#define SYSCONFDIR "$sysconfdir"
 
-#ifndef _DARWIN_USE_64_BIT_INODE
-# define _DARWIN_USE_64_BIT_INODE 1
-#endif
+#define OS_TARGET "${OS_TARGET}"
 ${config_h_extra}
 EOF
 
@@ -870,22 +1046,14 @@ fi
 echo "${w_config_h_extra_lines}
 #endif /* __W_CONFIGURE_CONFIG_H__ */" >> config.h
 
-#============================================================
+#==========================================================
 
 for infile in ${w_infiles}
 do
-	if [ -f ${infile}.in ] ; then
-		sed -e "s%@VERSION@%${VERSION}%g" \
-			-e "s%@PACKAGE@%${PACKAGE}%g" \
-			-e "s%@PACKAGE_URL@%${PACKAGE_URL}%g" \
-			${infile}.in > ${infile}
-	else
-		echo "WARNING: ${infile}.in doesn't exist"
-		printf "" > ${infile}
-	fi
+	./w_conf/00_standard_infile.sh ${infile}
 done
 
-#============================================================
+#==========================================================
 
 echo
 echo "* Now run 'make'  (or 'make clean' first if the app is already compiled)"
